# Generated by Django 6.0.7 on 2026-07-26 23:14

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_web', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion_web.factura',),
        ),
        migrations.CreateModel(
            name='PagoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion_web.pago',),
        ),
    ]
