# Generated by Django 5.2.17 on 2026-08-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='imagen',
            field=models.FileField(upload_to='comprobantes/'),
        ),
    ]
