# Generated by Django 6.0.7 on 2026-07-14 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario_Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=100)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Inventario de Bodega',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('contacto_nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='notas',
            new_name='notes',
        ),
        migrations.CreateModel(
            name='Insumo_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_web.producto')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_web.inventario_bodega')),
            ],
            options={
                'verbose_name_plural': 'Insumos por Producto',
            },
        ),
        migrations.AddField(
            model_name='inventario_bodega',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_web.proveedor'),
        ),
    ]
