# Generated by Django 6.0.7 on 2026-07-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_web', '0003_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('capacidad', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='insumo_producto',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_web.insumo'),
        ),
        migrations.AlterModelOptions(
            name='insumo',
            options={'verbose_name_plural': 'Insumos y Bodega'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='direccion_entrega',
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='gestion_web.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='insumos',
            field=models.ManyToManyField(related_name='productos', through='gestion_web.Insumo_Producto', to='gestion_web.insumo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('estado_envio', models.CharField(default='En camino', max_length=20)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='gestion_web.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='gestion_web.mesa'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='gestion_web.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='gestion_web.pago')),
            ],
        ),
        migrations.DeleteModel(
            name='Inventario_Bodega',
        ),
    ]
