# Generated by Django 6.0.7 on 2026-07-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_web', '0004_mesa_alter_insumo_producto_insumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
