# Generated by Django 6.0.7 on 2026-07-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_web', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PREPARANDO', 'En Cocina'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador (Dueño/Empleado)'), ('EMPLEADO', 'Empleado'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=12),
        ),
    ]
