# Generated by Django 6.0.7 on 2026-07-31 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_web', '0007_mesa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserva', to='gestion_web.pedido'),
        ),
    ]
