# Generated by Django 6.0.7 on 2026-07-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_web', '0008_reserva_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='acepta_politica_datos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_aceptacion_politica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='version_politica_datos',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
