# Generated by Django 6.0.7 on 2026-07-31 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_web', '0009_usuario_acepta_politica_datos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'verbose_name': 'Detalle de Pedido', 'verbose_name_plural': 'Detalles de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='entrega',
            options={'verbose_name': 'Entrega', 'verbose_name_plural': 'Entregas'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='insumo',
            options={'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos y Bodega'},
        ),
        migrations.AlterModelOptions(
            name='insumo_producto',
            options={'verbose_name': 'Insumo por Plato', 'verbose_name_plural': 'Insumos por Plato'},
        ),
        migrations.AlterModelOptions(
            name='mesa',
            options={'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Plato', 'verbose_name_plural': 'Platos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
