# Generated by Django 6.0.7 on 2026-08-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_web', '0010_alter_detallepedido_options_alter_entrega_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador (Dueño/Empleado)'), ('EMPLEADO', 'Empleado'), ('REPARTIDOR', 'Repartidor'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=12),
        ),
    ]
