# Generated by Django 5.2.17 on 2026-08-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_web', '0023_pago_confirmacion_repartidor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsitio',
            options={'verbose_name': 'Configuración del sitio', 'verbose_name_plural': 'Configuración del sitio'},
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si esta configuración está activa para la web pública.'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_botones',
            field=models.CharField(default='#FF9800', help_text='Color base para los botones principales.', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_encabezados',
            field=models.CharField(default='#212529', help_text='Color de títulos y encabezados.', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_enlaces',
            field=models.CharField(default='#D96600', help_text='Color de enlaces y acciones secundarias.', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_fondo',
            field=models.CharField(default='#FFFFFF', help_text='Color de fondo general del sitio.', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_menu',
            field=models.CharField(default='#F57C00', help_text='Color de navegación y menús.', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_principal',
            field=models.CharField(default='#F57C00', help_text='Color principal del sistema.', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_secundario',
            field=models.CharField(default='#B71C1C', help_text='Color secundario para contrastes o acentos.', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_texto',
            field=models.CharField(default='#212529', help_text='Color principal del texto del sitio.', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='correo',
            field=models.EmailField(blank=True, default='', help_text='Correo electrónico de contacto.', max_length=150),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='direccion',
            field=models.CharField(blank=True, default='', help_text='Dirección física del restaurante.', max_length=220),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='facebook',
            field=models.URLField(blank=True, default='', help_text='URL de Facebook del restaurante.', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='horario',
            field=models.CharField(blank=True, default='Lun - Dom: 11:00 - 22:00', help_text='Horario de atención general del restaurante.', max_length=150),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='imagen_portada',
            field=models.ImageField(blank=True, help_text='Imagen principal de portada de la página de inicio.', null=True, upload_to='portada/'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='instagram',
            field=models.URLField(blank=True, default='', help_text='URL de Instagram del restaurante.', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='nombre_restaurante',
            field=models.CharField(default='Ricas Papas Mary', help_text='Nombre visible del restaurante en la web.', max_length=120),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='subtitulo_inicio',
            field=models.CharField(default='Papas, combos y sabores para cada momento.', help_text='Subtítulo principal de la portada.', max_length=180),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='telefono',
            field=models.CharField(blank=True, default='', help_text='Teléfono principal de contacto.', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='texto_bienvenida',
            field=models.TextField(blank=True, default='Disfruta lo mejor de la cocina en Ricas Papas Mary.', help_text='Texto de bienvenida en la portada.'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='texto_informativo',
            field=models.TextField(blank=True, default='', help_text='Texto informativo que aparece junto a la información del negocio.'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='tiktok',
            field=models.URLField(blank=True, default='', help_text='URL de TikTok del restaurante.', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='titulo_inicio',
            field=models.CharField(default='Ricas Papas Mary', help_text='Título principal mostrado en la parte superior de la portada.', max_length=120),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='whatsapp',
            field=models.CharField(blank=True, default='', help_text='Número de WhatsApp del restaurante.', max_length=20),
        ),
    ]
