# Generated by Django 5.2.17 on 2026-09-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_web', '0024_alter_configuracionsitio_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'CONFIRMADA'), ('mesa__isnull', False)), fields=('mesa', 'fecha', 'hora'), name='unique_confirmada_mesa_fecha_hora'),
        ),
    ]
