# Generated by Django 5.0 on 2026-09-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_web', '0026_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='mapa_iframe_url',
            field=models.URLField(
                blank=True,
                default='',
                help_text='URL de inserción (embed) de Google Maps para el pie de página.',
                max_length=500,
            ),
        ),
    ]
