# Generated by Django 6.0.7 on 2026-07-26 23:14

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_web', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedidoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion_web.detallepedido',),
        ),
        migrations.CreateModel(
            name='PedidoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion_web.pedido',),
        ),
    ]
