# Generated by Django 6.0.7 on 2026-07-26 23:14

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_web', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoProductoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Insumo por Producto',
                'verbose_name_plural': 'Insumos por Producto',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion_web.insumo_producto',),
        ),
        migrations.CreateModel(
            name='InsumoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion_web.insumo',),
        ),
    ]
