# Generated by Django 6.0.7 on 2026-07-31 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoproxy',
            options={'verbose_name': 'Plato', 'verbose_name_plural': 'Platos'},
        ),
    ]
